state_estimation_node:
  ros__parameters:
    frequency: 30.0

    odom_frame: odom
    world_frame: odom
    base_link_frame: base_link

    imu0: l3gd20_gyro
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  true , true , true ,
                  false, false, false]
